### ISSUE TITLE
Plugin's dead

### ISSUE THREAD

**Issue by sanscriptum** [matthewn4444/Waifu2x-Image-Saver#1]
The target site now requires captcha and therefore refuses all incoming requests (https://github.com/nagadomi/waifu2x/issues/190)

So is it possible to make this plugin to ask for captcha so that you could complete it and then make it work for a while before it asks for captcha again?

**Comment by matthewn4444** [comment]
I am currently (slowly) writing a new version (from scratch) using jsm (Firefox's support for web extension is too early). Also it is hard to test on newer versions without getting signed. I can post my current version but its buggy (but it somewhat works). I switched the host to https://waifu2x.booru.pics/ since its easier and faster to work with.

Edit: I added a new release for super early version in release page, you can try using it if you like, there are issues with it but it is usable.

**Comment by sanscriptum** [comment]
Hey, thanks. Glad to see that project is not completely dead yet.

**Comment by matthewn4444** [comment]
Firefox continuous change in extension support sucks

**Comment by sanscriptum** [comment]
Currently there's a problem with ``:orig`` links from twitter, site cannot parse them and it gets stuck.

**Comment by matthewn4444** [comment]
I'll keep note of that
